"""DQN (Deep Q-Network) -- YOUR IMPLEMENTATION GOES HERE.

DQN is the odd one out in this project: it is *value-based* and *off-policy*,
where REINFORCE/A2C/PPO are policy-gradient methods. Implementing it teaches the
other half of the RL map -- replay buffers, target networks, and bootstrapped
TD targets.

The idea
--------
Learn an action-value function Q(s, a) and act greedily (with epsilon-greedy
exploration) with respect to it. Train Q to satisfy the Bellman equation using a
slowly-updated *target network* for stability:

    y_t = r_t + gamma * max_{a'} Q_target(s_{t+1}, a')   (0 if s_t was terminal)
    loss = SmoothL1( Q(s_t, a_t), y_t )

Key machinery (different from the policy-gradient agents)
---------------------------------------------------------
* **Replay buffer**: store transitions (s, a, r, s', done, next_mask) and sample
  random minibatches to break temporal correlation. The training loop in this
  project hands you whole trajectories; push their transitions into your buffer
  inside `learn`, then sample and update.
* **Target network**: a periodically-copied clone of Q used to compute y_t.
* **Epsilon-greedy**: `act` returns a random legal action with prob epsilon,
  else argmax Q over **legal** actions.

Masking with Q-values (read this twice)
---------------------------------------
Masking is different for value-based methods than for policy gradients:
* In `act`, take the argmax over legal actions only -- set Q of illegal actions
  to -inf before the argmax.
* In the **TD target**, the `max_{a'} Q_target(s', a')` must also be restricted
  to actions legal in s'. That is why transitions store `next_mask`. Forgetting
  this lets the target leak value through illegal actions and quietly wrecks
  training. (You will need to extend the stored data with next-state info, or
  reconstruct it -- a good design exercise.)

A caution on self-play + off-policy
-----------------------------------
DQN's replay buffer holds transitions generated by *old* versions of the policy
(and old opponents). In self-play that staleness is more pronounced than for the
on-policy methods. Smaller buffers, target updates, and patience help. This is a
genuinely harder setting than CartPole -- don't be discouraged if PPO is the one
that ultimately plays best.

References
----------
* Mnih et al. (2015), "Human-level control through deep RL" (Nature DQN).
* van Hasselt et al. (2016), Double DQN -- an easy, worthwhile upgrade.
* ``docs/implementing_algorithms.md``.
"""

from __future__ import annotations

import torch  # noqa: F401

from ..agents.base import Agent, Trajectory
from ..env.euchre_env import EuchreEnv


class DQNAgent(Agent):
    def __init__(
        self,
        obs_dim: int = EuchreEnv.observation_dim,
        n_actions: int = EuchreEnv.num_actions,
        hidden_dim: int = 256,
        lr: float = 1e-4,
        gamma: float = 0.99,
        buffer_size: int = 50_000,
        batch_size: int = 256,
        target_update_every: int = 500,
        epsilon_start: float = 1.0,
        epsilon_end: float = 0.05,
        epsilon_decay_steps: int = 50_000,
        device: str = "cpu",
    ) -> None:
        self.gamma = gamma
        self.batch_size = batch_size
        self.target_update_every = target_update_every
        self.device = torch.device(device)
        self.n_actions = n_actions
        # TODO(you): build the online Q-network and a target clone (load the same
        # weights, set target to eval mode), an Adam optimizer, a replay buffer
        # (a deque of transitions works), an epsilon schedule, and a step counter.
        raise NotImplementedError("Build the Q-networks, optimizer, and replay buffer here.")

    def act(self, observation, action_mask, info=None, *, deterministic=False) -> int:
        # TODO(you):
        #  - With prob epsilon (unless `deterministic`), return a random LEGAL action.
        #  - Else compute Q(s), set illegal actions to -inf, return the argmax.
        #  - Decay epsilon as steps accumulate.
        raise NotImplementedError

    def learn(self, batch: list[Trajectory]) -> dict[str, float]:
        # TODO(you):
        #  1. Push every transition into the replay buffer. NOTE: to build TD
        #     targets you need s', done, and next_mask for each transition; the
        #     base Transition does not store next-state, so either thread it
        #     through (extend collection) or pair consecutive transitions here.
        #  2. If the buffer is large enough, sample a minibatch.
        #  3. Compute y_t with the target net (masking next-state actions!).
        #  4. SmoothL1 loss against Q(s_t, a_t); backprop; step.
        #  5. Every `target_update_every` steps, copy weights to the target net.
        #  6. Return metrics.
        raise NotImplementedError
